import './globals.css'
import '../../components/Navbar'
import { Inter } from 'next/font/google'
import Navbar from '../../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pharmacd',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>
    <Navbar />
  )
}
