import BestChoiceContainer from '../../components/BestChoice'
import TestimonialsContainer from '../../components/Testimonials';
import Card from '../../components/Card'
import './globals.css'
import { Inter } from 'next/font/google'
 
 
 

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
 
    <>
           <BestChoiceContainer/>
           <TestimonialsContainer />
    </>
 
  )
}
